FORMAT: 1A

# Organising, Swiftly
_Organising_ is an outliner/todo list with strong search functionality.

## Node Collection [/nodes]

### Root node and all children [GET]
Returns the root node, with all of its children.

+ Response 200 (application/json)

        [{
            "ID": 0,
            "text": "Update repo",
            "completed": false,
            "children": [
                {
                    "ID": 1,
                    "text": "Commit changes",
                    "completed": true
                }, {
                    "ID": 2,
                    "text": "Push to origin",
                    "completed": false
                }
            ]
        }]